# Generated by Django 3.2.18 on 2023-03-24 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('audience', models.IntegerField(null=True)),
                ('release_data', models.DateField(null=True)),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Horror', 'Horror')], max_length=30)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('poster_url', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('actor_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
