# Generated by Django 3.1.7 on 2023-04-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='question',
        ),
    ]
